<a href="https://colab.research.google.com/github/Talha1818/PyTorch/blob/master/tensors_in_pytorch_20Mar25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.6.0+cu124


In [ ]:
if torch.cuda.is_available():
    print(f"GPU is available: Using GPU {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available: Using CPU")

GPU not available: Using CPU


# Creating a Tensors

In [ ]:
# using empty
x = torch.empty(2,3)
x

tensor([[-1.3725e-08,  4.5081e-41,  1.4474e-33],
        [ 0.0000e+00,  4.4842e-44,  0.0000e+00]])

In [ ]:
# check type
type(x)

torch.Tensor

In [ ]:
# using zeros
x = torch.zeros(2,3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# using ones
x = torch.ones(2,3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# using rand
x = torch.rand(2,3)
x

tensor([[0.1295, 0.2777, 0.3039],
        [0.4123, 0.3568, 0.5290]])

In [ ]:
# using rand
x = torch.rand(2,3)
x

tensor([[0.6176, 0.5764, 0.1547],
        [0.3190, 0.4678, 0.2417]])

In [ ]:
# using manual seed
torch.manual_seed(1)
x = torch.rand(2,3)
x

tensor([[0.7576, 0.2793, 0.4031],
        [0.7347, 0.0293, 0.7999]])

In [ ]:
# using manual seed
torch.manual_seed(1)
x = torch.rand(2,3)
x

tensor([[0.7576, 0.2793, 0.4031],
        [0.7347, 0.0293, 0.7999]])

In [ ]:
# using tensors
x = torch.tensor([[1,2,3],[3,4,5]])
x

tensor([[1, 2, 3],
        [3, 4, 5]])

In [ ]:
# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


#Check Shapes of Tensors

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
a  = torch.empty_like(x)
b = torch.zeros_like(x)
c = torch.ones_like(x)
d = torch.rand_like(x, dtype=torch.float)

print("empty like: \n", a)
print("zeros like: \n", b)
print("ones like: \n", c)
print("rand like: \n", d)

empty like: 
 tensor([[              0,              81,       173165936],
        [138176386288928,               0,               0]])
zeros like: 
 tensor([[0, 0, 0],
        [0, 0, 0]])
ones like: 
 tensor([[1, 1, 1],
        [1, 1, 1]])
rand like: 
 tensor([[0.6826, 0.3051, 0.4635],
        [0.4550, 0.5725, 0.4980]])


# Check Data Types of Tensors

In [ ]:
# find data type
x.dtype

torch.int64

In [ ]:
# assign data type
a = torch.tensor([1.0,2.0,3.0], dtype=torch.int32)
b = torch.tensor([1.0,2.0,3.0], dtype=torch.float32)
c = torch.tensor([1.0,2.0,3.0], dtype=torch.double)
print(a.dtype,":", a)
print(b.dtype,":", b)
print(c.dtype,":", c)

torch.int32 : tensor([1, 2, 3], dtype=torch.int32)
torch.float32 : tensor([1., 2., 3.])
torch.float64 : tensor([1., 2., 3.], dtype=torch.float64)


In [ ]:
x.dtype

torch.int64

In [ ]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


# Mathematical Operations

In [ ]:
x = torch.rand(2,2)
x

tensor([[0.9371, 0.6556],
        [0.3138, 0.1980]])

In [ ]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.8781, 0.4298],
        [0.0985, 0.0392]])

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.4162, 0.2843, 0.3398],
        [0.5239, 0.7981, 0.7718]])
tensor([[0.0112, 0.8100, 0.6397],
        [0.9743, 0.8300, 0.0444]])


In [ ]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.0009, 0.2843, 0.3398],
        [0.5239, 0.7981, 0.0164]])

In [ ]:
c = torch.tensor([1, -2, 3, -4])

In [ ]:
# abs
a = torch.abs(c)
# negative
b = torch.neg(c)

print("absolute:", a)
print("negative:", b)

d = torch.tensor([1.9, 2.3, 3.7, 4.4])

# round
a = torch.round(d)
# ceil
b = torch.ceil(d)
# floor
c = torch.floor(d)
# clamp
d = torch.clamp(d, min=2, max=3)

print("round:", a)
print("ceil:", b)
print("floor:", c)
print("clamp:", d)

absolute: tensor([1, 2, 3, 4])
negative: tensor([-1,  2, -3,  4])
round: tensor([2., 2., 4., 4.])
ceil: tensor([2., 3., 4., 5.])
floor: tensor([1., 2., 3., 4.])
clamp: tensor([2.0000, 2.3000, 3.0000, 3.0000])


In [ ]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[5., 9., 5.],
        [3., 3., 5.]])

In [ ]:
# sum
a = torch.sum(e)
# sum along columns
b = torch.sum(e, dim=0)
# sum along rows
c = torch.sum(e, dim=1)

# mean
d = torch.mean(e)
# mean along col
ee = torch.mean(e, dim=0)

# median
f = torch.median(e)

# max and min
g = torch.max(e)
h = torch.min(e)

# product
i = torch.prod(e)

# standard deviation
j = torch.std(e)

# variance
k = torch.var(e)

# argmax
l = torch.argmax(e)

# argmin
m = torch.argmin(e)

print("sum:", a)
print("sum along columns:", b)
print("sum along rows:", c)
print("mean:", d)
print("mean along columns:", ee)
print("median:", f)
print("max:", g)
print("min:", h)
print("product:", i)
print("standard deviation:", j)
print("variance:", k)
print("argmax:", l)
print("argmin:", m)

sum: tensor(30.)
sum along columns: tensor([ 8., 12., 10.])
sum along rows: tensor([19., 11.])
mean: tensor(5.)
mean along columns: tensor([4., 6., 5.])
median: tensor(5.)
max: tensor(9.)
min: tensor(3.)
product: tensor(10125.)
standard deviation: tensor(2.1909)
variance: tensor(4.8000)
argmax: tensor(1)
argmin: tensor(3)
